apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kafka-keyvalue
    context: .
    custom:
      buildCommand: y-build --opt target=jvm
      dependencies:
        dockerfile:
          path: ./Dockerfile
deploy:
  kustomize:
    paths:
    - ./k8s
profiles:
- name: prod-build
  patches:
  - op: replace
    path: /build/artifacts/0/custom/buildCommand
    value: y-build
