apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kafka-keyvalue
    context: .
    # docker:
    #   target: jvm
    #   buildArgs:
    #     build: package
    custom:
      buildCommand: y-build --opt target=jvm --opt build-arg:build=package
      dependencies:
        dockerfile:
          path: ./Dockerfile
deploy:
  kustomize:
    paths:
    - ./test
profiles:
- name: prod-build
  patches:
  - op: replace
    path: /build/artifacts/0/custom/buildCommand
    value: y-build
