apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kafka-keyvalue
    context: .
    # docker:
    #   target: jvm
    #   buildArgs:
    #     build: package
    custom:
      buildCommand: y-build --opt target=jvm build-arg:build=package
      dependencies:
        dockerfile:
          path: ./Dockerfile
deploy:
  # kustomize:
  #   paths:
  #   - ./test
  # kustomization.yaml currently sets the prod image
  kubectl:
    manifests:
    - ./test/
profiles:
- name: prod-build
  patches:
  - op: replace
    path: /build/artifacts/0/custom/buildCommand
    value: y-build
