apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kafka-keyvalue
    context: .
    custom:
      buildCommand: y-build --opt target=dev
      dependencies:
        dockerfile:
          path: ./Dockerfile
    # Full source sync messes up consumer init, and we're yet to experiment with which subsets we can sync
    #sync:
    #  manual:
    #  - src: src/main/**
    #    dest: .
profiles:
- name: prod-build
  patches:
  - op: replace
    path: /build/artifacts/0/custom/buildCommand
    value: y-build
