bases:
# It's slow to re-apply the kafka stack on every skaffold dev, needs to be automated outside this skaffold
# - github.com/Yolean/kubernetes-kafka/variants/dev-small?ref=v6.0.0
resources:
- ./bash.yaml
- ./topic-test-kkv-1.yaml
